### ISSUE TITLE
Output argument "st_letter" not assigned a value in the execution with "f_GetLetterSize" function

### ISSUE THREAD

**Issue by rahilvaknalli** [BSP-Uniandes/RIPPLELAB#18]
Hi, I am getting an error on Line 65 of p_RippleLab.m when I attempt to run it on MATLAB. Any ideas on how to fix this issue? I think I have the path correctly set on Matlab.

**Comment by wangmy66** [comment]
I have the same problem.Anyone who can help to solve it please.

**Comment by DahalRizu** [comment]
Did any body solve this issue? it would be a great help

**Comment by mnavarretem** [comment]
This is related to the main script not being able to access RippleLab subfolders. To be sure, you can add all RippleLab files into the path:

Add RippleLab files to the MATLAB path: [Home > Set Path > Add with subfolders]

or typing in the command window:
addpath(genpath(c:/~your-RippleLab-basefolder))

**Comment by wangmy66** [comment]
Firstly,it's a great honor for me to receive the reply from you. However,I'm sure that I had add RippleLab files to the MATLAB path: [Home &gt; Set Path &gt; Add with subfolders], but I still can't use the software.Please send me an answer at your convenience.



---Original---
From: ***@***.***&gt;
Date: Fri, Apr 7, 2023 23:36 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [BSP-Uniandes/RIPPLELAB] Output argument "st_letter" not assigneda value in the execution with "f_GetLetterSize" function (Issue #18)




 
This is related to the main script not being able to access RippleLab subfolders. To be sure, you can add all RippleLab files into the path:
 
Add RippleLab files to the MATLAB path: [Home &gt; Set Path &gt; Add with subfolders]
 
or typing in the command window:
 addpath(genpath(c:/~your-RippleLab-basefolder))

**Comment by rahilvaknalli** [comment]
I noticed that it could be an error in the screen resolution. If you comment out the screen resolution for your device in f_GetLetterSize, you are able to still run the GUI with the text being slightly off.
