### ISSUE TITLE
Output argument "st_letter" not assigned a value in the execution with "f_GetLetterSize" function 

### ISSUE THREAD

**Issue by DahalRizu** [BSP-Uniandes/RIPPLELAB#19]
How do i fix this?

when i try to run ripple lab, it shows 

Output argument "st_letter" not assigned a value in the execution with "f_GetLetterSize" function

**Comment by mnavarretem** [comment]
This is related to the main script not being able to access RippleLab subfolders. To be sure, you can add all RippleLab files into the path:

Add RippleLab files to the MATLAB path: [Home > Set Path > Add with subfolders]

or typing in the command window:
addpath(genpath(c:/~your-RippleLab-basefolder))
